name: Run Python Script on Schedule

on:
  workflow_dispatch: 
  schedule:
    # Runs at 12:00 AM UTC every day (adjust cron expression as needed)
    - cron: "10 0 * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run your Python script
      - name: Run Python Script
        run: |
          python revenue_tracker_dtb_lumens_combine.py
      # Step 5: Commit and push the changes
      - name: Commit and push CSV results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lumens_combined_data.csv  # Replace with the path to the CSV file you generated
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add CSV results generated by Python script"
            git push
          fi
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          # You must set the GitHub token to authenticate the push command
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
